version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: web
      APP_PORT: 80

  web:
    image: ghcr.io/fetedays/http-file-server:1.0.1
    restart: on-failure
    stop_grace_period: 1m

    environment:
      MEDIA_ROOT: /data/media
      CONFIG_DIR: /data/config

    volumes:
      - ${APP_DATA_DIR}/config:/data/config
      - ${APP_DATA_DIR}/media:/data/media/local

      # NAS를 사용하는 경우
      # - /mnt/nas/music:/data/media/nas-music:ro

      # USB를 사용하는 경우
      # - /media/umbrel/usb1:/data/media/usb1:ro
